name: Build and Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # or your preferred Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Push to Hostinger
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: hostinger-deploy
          FOLDER: .output # or 'dist' if you're using an older Nuxt version
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Deploy: ({sha}) {msg}"